#!/bin/bash

# Generate route registration for all modules

INTERNAL_DIR="../internal"
OUTPUT_FILE="../cmd/api/routes_generated.go"

echo "// Code generated by generate_routes.sh. DO NOT EDIT." > "$OUTPUT_FILE"
echo "package main" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "import (" >> "$OUTPUT_FILE"
echo '	"github.com/go-chi/chi/v5"' >> "$OUTPUT_FILE"
echo '	"github.com/jackc/pgx/v5/pgxpool"' >> "$OUTPUT_FILE"
echo '	"github.com/your-org/pos-backend/internal/logging"' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Find all modules with service.go, handler.go, and routes.go
MODULES=()
for dir in "$INTERNAL_DIR"/*/ ; do
	module=$(basename "$dir")

	# Skip special directories
	if [[ "$module" == "pkg" || "$module" == "internal.old" || \
	      "$module" == "auth" || "$module" == "config" || \
	      "$module" == "http" || "$module" == "logging" || \
	      "$module" == "metrics" || "$module" == "middleware" || \
	      "$module" == "repository" || "$module" == "api" ]]; then
		continue
	fi

	# Check for required files
	if [[ -f "$dir/service.go" && -f "$dir/handler.go" && -f "$dir/routes.go" ]]; then
		echo "	\"github.com/your-org/pos-backend/internal/$module\"" >> "$OUTPUT_FILE"
		MODULES+=("$module")
	fi
done

echo ")" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Generate registration function
echo "// RegisterAllModuleRoutes registers routes for all ${#MODULES[@]} modules" >> "$OUTPUT_FILE"
echo "func RegisterAllModuleRoutes(r chi.Router, db *pgxpool.Pool, logger *logging.Logger) {" >> "$OUTPUT_FILE"

for module in "${MODULES[@]}"; do
	echo "" >> "$OUTPUT_FILE"
	echo "	// Register $module routes" >> "$OUTPUT_FILE"
	echo "	{" >> "$OUTPUT_FILE"
	echo "		repo := ${module}.NewRepository()" >> "$OUTPUT_FILE"
	echo "		svc := ${module}.NewService(repo, db, logger)" >> "$OUTPUT_FILE"
	echo "		handler := ${module}.NewHandler(svc, logger)" >> "$OUTPUT_FILE"
	echo "		${module}.RegisterRoutes(r, handler)" >> "$OUTPUT_FILE"
	echo "		${module}.RegisterAdminRoutes(r, handler)" >> "$OUTPUT_FILE"
	echo "	}" >> "$OUTPUT_FILE"
done

echo "" >> "$OUTPUT_FILE"
echo "	logger.Info(\"registered routes for ${#MODULES[@]} modules\")" >> "$OUTPUT_FILE"
echo "}" >> "$OUTPUT_FILE"

echo "✅ Generated $OUTPUT_FILE with ${#MODULES[@]} modules"
echo "Modules: ${MODULES[*]}"
