package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const registrationTemplate = `// Code generated by generate_route_registration.go. DO NOT EDIT.
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/your-org/pos-backend/internal/logging"

{{range .Modules}}	"github.com/your-org/pos-backend/internal/{{.}}"
{{end}})

// RegisterAllModuleRoutes registers all module routes
func RegisterAllModuleRoutes(r chi.Router, db *pgxpool.Pool, logger *logging.Logger) {
{{range .Modules}}
	// Register {{.}} routes
	{
		repo := {{.}}.NewRepository()
		svc := {{.}}.NewService(repo, db, logger)
		handler := {{.}}.NewHandler(svc, logger)
		{{.}}.RegisterRoutes(r, handler)
		{{.}}.RegisterAdminRoutes(r, handler)
	}
{{end}}
	logger.Info("registered routes for {{.Count}} modules")
}
`

type TemplateData struct {
	Modules []string
	Count   int
}

func main() {
	baseDir := "../internal"

	// Get all module directories
	modules, err := getModuleDirs(baseDir)
	if err != nil {
		fmt.Printf("Error getting modules: %v\n", err)
		os.Exit(1)
	}

	sort.Strings(modules)

	data := TemplateData{
		Modules: modules,
		Count:   len(modules),
	}

	// Generate registration file
	tmpl, err := template.New("registration").Parse(registrationTemplate)
	if err != nil {
		fmt.Printf("Error parsing template: %v\n", err)
		os.Exit(1)
	}

	outputFile := "../cmd/api/routes_generated.go"
	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Printf("Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	err = tmpl.Execute(f, data)
	if err != nil {
		fmt.Printf("Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Generated %s with %d modules\n", outputFile, len(modules))
	fmt.Printf("   Modules: %s\n", strings.Join(modules, ", "))
}

func getModuleDirs(baseDir string) ([]string, error) {
	var modules []string

	entries, err := ioutil.ReadDir(baseDir)
	if err != nil {
		return nil, err
	}

	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), ".") {
			// Skip special directories
			if entry.Name() == "pkg" || entry.Name() == "internal.old" ||
			   entry.Name() == "auth" || entry.Name() == "config" ||
			   entry.Name() == "http" || entry.Name() == "logging" ||
			   entry.Name() == "metrics" || entry.Name() == "middleware" ||
			   entry.Name() == "repository" {
				continue
			}

			// Check if it has required files
			servicePath := filepath.Join(baseDir, entry.Name(), "service.go")
			handlerPath := filepath.Join(baseDir, entry.Name(), "handler.go")
			routesPath := filepath.Join(baseDir, entry.Name(), "routes.go")

			if fileExists(servicePath) && fileExists(handlerPath) && fileExists(routesPath) {
				modules = append(modules, entry.Name())
			}
		}
	}

	return modules, nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}
