// Code generated by generate_routes.sh. DO NOT EDIT.
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/your-org/pos-backend/internal/logging"

	"github.com/your-org/pos-backend/internal/account_subtype"
	"github.com/your-org/pos-backend/internal/account_type"
	"github.com/your-org/pos-backend/internal/accounting_period"
	"github.com/your-org/pos-backend/internal/analytic_account"
	"github.com/your-org/pos-backend/internal/analytic_plan"
	"github.com/your-org/pos-backend/internal/api_key"
	"github.com/your-org/pos-backend/internal/api_request_log"
	"github.com/your-org/pos-backend/internal/asset_category"
	"github.com/your-org/pos-backend/internal/asset_depreciation_schedule"
	"github.com/your-org/pos-backend/internal/audit_log"
	"github.com/your-org/pos-backend/internal/background_job"
	"github.com/your-org/pos-backend/internal/bank_account"
	"github.com/your-org/pos-backend/internal/bank_reconciliation"
	"github.com/your-org/pos-backend/internal/bank_reconciliation_item"
	"github.com/your-org/pos-backend/internal/bank_statement"
	"github.com/your-org/pos-backend/internal/bank_statement_line"
	"github.com/your-org/pos-backend/internal/bank_statement_reconciliation"
	"github.com/your-org/pos-backend/internal/batch_transaction"
	"github.com/your-org/pos-backend/internal/budget"
	"github.com/your-org/pos-backend/internal/budget_line"
	"github.com/your-org/pos-backend/internal/cash_drawer"
	"github.com/your-org/pos-backend/internal/cash_drawer_session"
	"github.com/your-org/pos-backend/internal/cash_movement"
	"github.com/your-org/pos-backend/internal/category"
	"github.com/your-org/pos-backend/internal/chart_of_account"
	"github.com/your-org/pos-backend/internal/cours"
	"github.com/your-org/pos-backend/internal/currency"
	"github.com/your-org/pos-backend/internal/currency_rate"
	"github.com/your-org/pos-backend/internal/customer"
	"github.com/your-org/pos-backend/internal/customer_address"
	"github.com/your-org/pos-backend/internal/customer_invoice"
	"github.com/your-org/pos-backend/internal/customer_invoice_line"
	"github.com/your-org/pos-backend/internal/customer_payment"
	"github.com/your-org/pos-backend/internal/customer_payment_application"
	"github.com/your-org/pos-backend/internal/customer_store_credit_account"
	"github.com/your-org/pos-backend/internal/customer_tier_history"
	"github.com/your-org/pos-backend/internal/cycle_count"
	"github.com/your-org/pos-backend/internal/cycle_count_item"
	"github.com/your-org/pos-backend/internal/data_export_request"
	"github.com/your-org/pos-backend/internal/deferred_expense_contract"
	"github.com/your-org/pos-backend/internal/deferred_expense_schedule"
	"github.com/your-org/pos-backend/internal/deferred_revenue_contract"
	"github.com/your-org/pos-backend/internal/deferred_revenue_schedule"
	"github.com/your-org/pos-backend/internal/delivery_assignment"
	"github.com/your-org/pos-backend/internal/delivery_driver"
	"github.com/your-org/pos-backend/internal/delivery_zone"
	"github.com/your-org/pos-backend/internal/device"
	"github.com/your-org/pos-backend/internal/document_sequence"
	"github.com/your-org/pos-backend/internal/driver_shift"
	"github.com/your-org/pos-backend/internal/e_invoicing_document"
	"github.com/your-org/pos-backend/internal/e_invoicing_document_event"
	"github.com/your-org/pos-backend/internal/email_queue"
	"github.com/your-org/pos-backend/internal/employee_schedule"
	"github.com/your-org/pos-backend/internal/expens"
	"github.com/your-org/pos-backend/internal/external_order_mapping"
	"github.com/your-org/pos-backend/internal/file_attachment"
	"github.com/your-org/pos-backend/internal/fiscal_position"
	"github.com/your-org/pos-backend/internal/fiscal_position_tax_mapping"
	"github.com/your-org/pos-backend/internal/fiscal_year"
	"github.com/your-org/pos-backend/internal/fixed_asset"
	"github.com/your-org/pos-backend/internal/floor_plan"
	"github.com/your-org/pos-backend/internal/general_ledger"
	"github.com/your-org/pos-backend/internal/gift_card"
	"github.com/your-org/pos-backend/internal/gift_card_transaction"
	"github.com/your-org/pos-backend/internal/goods_receipt"
	"github.com/your-org/pos-backend/internal/goods_receipt_item"
	"github.com/your-org/pos-backend/internal/immutability_violations_log"
	"github.com/your-org/pos-backend/internal/integration_config"
	"github.com/your-org/pos-backend/internal/inventory_cost_layer"
	"github.com/your-org/pos-backend/internal/inventory_transaction"
	"github.com/your-org/pos-backend/internal/inventory_transfer"
	"github.com/your-org/pos-backend/internal/inventory_transfer_item"
	"github.com/your-org/pos-backend/internal/inventory_valuation_setting"
	"github.com/your-org/pos-backend/internal/invoice_payment_schedule"
	"github.com/your-org/pos-backend/internal/journal"
	"github.com/your-org/pos-backend/internal/journal_entry"
	"github.com/your-org/pos-backend/internal/journal_entry_line"
	"github.com/your-org/pos-backend/internal/journal_entry_type"
	"github.com/your-org/pos-backend/internal/kitchen_station"
	"github.com/your-org/pos-backend/internal/kitchen_ticket"
	"github.com/your-org/pos-backend/internal/localization_package"
	"github.com/your-org/pos-backend/internal/location"
	"github.com/your-org/pos-backend/internal/loyalty_points_rule"
	"github.com/your-org/pos-backend/internal/loyalty_points_transaction"
	"github.com/your-org/pos-backend/internal/loyalty_redemption"
	"github.com/your-org/pos-backend/internal/loyalty_reward"
	"github.com/your-org/pos-backend/internal/loyalty_tier"
	"github.com/your-org/pos-backend/internal/loyalty_tier_benefit"
	"github.com/your-org/pos-backend/internal/modifier"
	"github.com/your-org/pos-backend/internal/modifier_group"
	"github.com/your-org/pos-backend/internal/notification"
	"github.com/your-org/pos-backend/internal/notification_preference"
	"github.com/your-org/pos-backend/internal/order"
	"github.com/your-org/pos-backend/internal/order_item"
	"github.com/your-org/pos-backend/internal/order_item_modifier"
	"github.com/your-org/pos-backend/internal/order_tracking_event"
	"github.com/your-org/pos-backend/internal/organization"
	"github.com/your-org/pos-backend/internal/organization_feature"
	"github.com/your-org/pos-backend/internal/organization_setting"
	"github.com/your-org/pos-backend/internal/payment"
	"github.com/your-org/pos-backend/internal/payment_term"
	"github.com/your-org/pos-backend/internal/payment_term_line"
	"github.com/your-org/pos-backend/internal/permission"
	"github.com/your-org/pos-backend/internal/pos_account_mapping"
	"github.com/your-org/pos-backend/internal/pos_error_log"
	"github.com/your-org/pos-backend/internal/pos_posting_audit"
	"github.com/your-org/pos-backend/internal/pos_session"
	"github.com/your-org/pos-backend/internal/pos_tax_mapping"
	"github.com/your-org/pos-backend/internal/posting_concept"
	"github.com/your-org/pos-backend/internal/posting_concept_override"
	"github.com/your-org/pos-backend/internal/posting_document_type"
	"github.com/your-org/pos-backend/internal/posting_profile"
	"github.com/your-org/pos-backend/internal/posting_profile_document"
	"github.com/your-org/pos-backend/internal/posting_rule"
	"github.com/your-org/pos-backend/internal/posting_rule_line"
	"github.com/your-org/pos-backend/internal/posting_validation_result"
	"github.com/your-org/pos-backend/internal/posting_validation_rule"
	"github.com/your-org/pos-backend/internal/price_list"
	"github.com/your-org/pos-backend/internal/price_list_item"
	"github.com/your-org/pos-backend/internal/printer_configuration"
	"github.com/your-org/pos-backend/internal/product"
	"github.com/your-org/pos-backend/internal/product_batch"
	"github.com/your-org/pos-backend/internal/product_component"
	"github.com/your-org/pos-backend/internal/product_modifier_group"
	"github.com/your-org/pos-backend/internal/product_serial_number"
	"github.com/your-org/pos-backend/internal/product_variant"
	"github.com/your-org/pos-backend/internal/promotion"
	"github.com/your-org/pos-backend/internal/promotion_usage"
	"github.com/your-org/pos-backend/internal/purchase_order"
	"github.com/your-org/pos-backend/internal/purchase_order_item"
	"github.com/your-org/pos-backend/internal/rate_limit"
	"github.com/your-org/pos-backend/internal/reconciliation_rule_model"
	"github.com/your-org/pos-backend/internal/reservation"
	"github.com/your-org/pos-backend/internal/restaurant_table"
	"github.com/your-org/pos-backend/internal/return_reason"
	"github.com/your-org/pos-backend/internal/role"
	"github.com/your-org/pos-backend/internal/role_permission"
	"github.com/your-org/pos-backend/internal/sale"
	"github.com/your-org/pos-backend/internal/sale_item"
	"github.com/your-org/pos-backend/internal/sale_return"
	"github.com/your-org/pos-backend/internal/sale_return_item"
	"github.com/your-org/pos-backend/internal/sales_channel"
	"github.com/your-org/pos-backend/internal/scheduled_report"
	"github.com/your-org/pos-backend/internal/shift"
	"github.com/your-org/pos-backend/internal/sms_queue"
	"github.com/your-org/pos-backend/internal/staff_commission"
	"github.com/your-org/pos-backend/internal/stock_adjustment_reason"
	"github.com/your-org/pos-backend/internal/store_credit_transaction"
	"github.com/your-org/pos-backend/internal/supplier"
	"github.com/your-org/pos-backend/internal/system_health"
	"github.com/your-org/pos-backend/internal/table_section"
	"github.com/your-org/pos-backend/internal/tax"
	"github.com/your-org/pos-backend/internal/tax_group"
	"github.com/your-org/pos-backend/internal/tax_report_definition"
	"github.com/your-org/pos-backend/internal/tax_report_line"
	"github.com/your-org/pos-backend/internal/time_clock_entry"
	"github.com/your-org/pos-backend/internal/tip_distribution"
	"github.com/your-org/pos-backend/internal/tip_pool"
	"github.com/your-org/pos-backend/internal/units_of_measure"
	"github.com/your-org/pos-backend/internal/uom_conversion"
	"github.com/your-org/pos-backend/internal/user"
	"github.com/your-org/pos-backend/internal/user_role"
	"github.com/your-org/pos-backend/internal/user_session"
	"github.com/your-org/pos-backend/internal/user_setting"
	"github.com/your-org/pos-backend/internal/vendor_bill"
	"github.com/your-org/pos-backend/internal/vendor_bill_line"
	"github.com/your-org/pos-backend/internal/vendor_payment"
	"github.com/your-org/pos-backend/internal/vendor_payment_application"
	"github.com/your-org/pos-backend/internal/webhook"
	"github.com/your-org/pos-backend/internal/webhook_delivery"
	"github.com/your-org/pos-backend/internal/your_table_name"
)

// RegisterAllModuleRoutes registers routes for all 171 modules
func RegisterAllModuleRoutes(r chi.Router, db *pgxpool.Pool, logger *logging.Logger) {

	// Register account_subtype routes
	{
		repo := account_subtype.NewRepository()
		svc := account_subtype.NewService(repo, db, logger)
		handler := account_subtype.NewHandler(svc, logger)
		account_subtype.RegisterRoutes(r, handler)
		account_subtype.RegisterAdminRoutes(r, handler)
	}

	// Register account_type routes
	{
		repo := account_type.NewRepository()
		svc := account_type.NewService(repo, db, logger)
		handler := account_type.NewHandler(svc, logger)
		account_type.RegisterRoutes(r, handler)
		account_type.RegisterAdminRoutes(r, handler)
	}

	// Register accounting_period routes
	{
		repo := accounting_period.NewRepository()
		svc := accounting_period.NewService(repo, db, logger)
		handler := accounting_period.NewHandler(svc, logger)
		accounting_period.RegisterRoutes(r, handler)
		accounting_period.RegisterAdminRoutes(r, handler)
	}

	// Register analytic_account routes
	{
		repo := analytic_account.NewRepository()
		svc := analytic_account.NewService(repo, db, logger)
		handler := analytic_account.NewHandler(svc, logger)
		analytic_account.RegisterRoutes(r, handler)
		analytic_account.RegisterAdminRoutes(r, handler)
	}

	// Register analytic_plan routes
	{
		repo := analytic_plan.NewRepository()
		svc := analytic_plan.NewService(repo, db, logger)
		handler := analytic_plan.NewHandler(svc, logger)
		analytic_plan.RegisterRoutes(r, handler)
		analytic_plan.RegisterAdminRoutes(r, handler)
	}

	// Register api_key routes
	{
		repo := api_key.NewRepository()
		svc := api_key.NewService(repo, db, logger)
		handler := api_key.NewHandler(svc, logger)
		api_key.RegisterRoutes(r, handler)
		api_key.RegisterAdminRoutes(r, handler)
	}

	// Register api_request_log routes
	{
		repo := api_request_log.NewRepository()
		svc := api_request_log.NewService(repo, db, logger)
		handler := api_request_log.NewHandler(svc, logger)
		api_request_log.RegisterRoutes(r, handler)
		api_request_log.RegisterAdminRoutes(r, handler)
	}

	// Register asset_category routes
	{
		repo := asset_category.NewRepository()
		svc := asset_category.NewService(repo, db, logger)
		handler := asset_category.NewHandler(svc, logger)
		asset_category.RegisterRoutes(r, handler)
		asset_category.RegisterAdminRoutes(r, handler)
	}

	// Register asset_depreciation_schedule routes
	{
		repo := asset_depreciation_schedule.NewRepository()
		svc := asset_depreciation_schedule.NewService(repo, db, logger)
		handler := asset_depreciation_schedule.NewHandler(svc, logger)
		asset_depreciation_schedule.RegisterRoutes(r, handler)
		asset_depreciation_schedule.RegisterAdminRoutes(r, handler)
	}

	// Register audit_log routes
	{
		repo := audit_log.NewRepository()
		svc := audit_log.NewService(repo, db, logger)
		handler := audit_log.NewHandler(svc, logger)
		audit_log.RegisterRoutes(r, handler)
		audit_log.RegisterAdminRoutes(r, handler)
	}

	// Register background_job routes
	{
		repo := background_job.NewRepository()
		svc := background_job.NewService(repo, db, logger)
		handler := background_job.NewHandler(svc, logger)
		background_job.RegisterRoutes(r, handler)
		background_job.RegisterAdminRoutes(r, handler)
	}

	// Register bank_account routes
	{
		repo := bank_account.NewRepository()
		svc := bank_account.NewService(repo, db, logger)
		handler := bank_account.NewHandler(svc, logger)
		bank_account.RegisterRoutes(r, handler)
		bank_account.RegisterAdminRoutes(r, handler)
	}

	// Register bank_reconciliation routes
	{
		repo := bank_reconciliation.NewRepository()
		svc := bank_reconciliation.NewService(repo, db, logger)
		handler := bank_reconciliation.NewHandler(svc, logger)
		bank_reconciliation.RegisterRoutes(r, handler)
		bank_reconciliation.RegisterAdminRoutes(r, handler)
	}

	// Register bank_reconciliation_item routes
	{
		repo := bank_reconciliation_item.NewRepository()
		svc := bank_reconciliation_item.NewService(repo, db, logger)
		handler := bank_reconciliation_item.NewHandler(svc, logger)
		bank_reconciliation_item.RegisterRoutes(r, handler)
		bank_reconciliation_item.RegisterAdminRoutes(r, handler)
	}

	// Register bank_statement routes
	{
		repo := bank_statement.NewRepository()
		svc := bank_statement.NewService(repo, db, logger)
		handler := bank_statement.NewHandler(svc, logger)
		bank_statement.RegisterRoutes(r, handler)
		bank_statement.RegisterAdminRoutes(r, handler)
	}

	// Register bank_statement_line routes
	{
		repo := bank_statement_line.NewRepository()
		svc := bank_statement_line.NewService(repo, db, logger)
		handler := bank_statement_line.NewHandler(svc, logger)
		bank_statement_line.RegisterRoutes(r, handler)
		bank_statement_line.RegisterAdminRoutes(r, handler)
	}

	// Register bank_statement_reconciliation routes
	{
		repo := bank_statement_reconciliation.NewRepository()
		svc := bank_statement_reconciliation.NewService(repo, db, logger)
		handler := bank_statement_reconciliation.NewHandler(svc, logger)
		bank_statement_reconciliation.RegisterRoutes(r, handler)
		bank_statement_reconciliation.RegisterAdminRoutes(r, handler)
	}

	// Register batch_transaction routes
	{
		repo := batch_transaction.NewRepository()
		svc := batch_transaction.NewService(repo, db, logger)
		handler := batch_transaction.NewHandler(svc, logger)
		batch_transaction.RegisterRoutes(r, handler)
		batch_transaction.RegisterAdminRoutes(r, handler)
	}

	// Register budget routes
	{
		repo := budget.NewRepository()
		svc := budget.NewService(repo, db, logger)
		handler := budget.NewHandler(svc, logger)
		budget.RegisterRoutes(r, handler)
		budget.RegisterAdminRoutes(r, handler)
	}

	// Register budget_line routes
	{
		repo := budget_line.NewRepository()
		svc := budget_line.NewService(repo, db, logger)
		handler := budget_line.NewHandler(svc, logger)
		budget_line.RegisterRoutes(r, handler)
		budget_line.RegisterAdminRoutes(r, handler)
	}

	// Register cash_drawer routes
	{
		repo := cash_drawer.NewRepository()
		svc := cash_drawer.NewService(repo, db, logger)
		handler := cash_drawer.NewHandler(svc, logger)
		cash_drawer.RegisterRoutes(r, handler)
		cash_drawer.RegisterAdminRoutes(r, handler)
	}

	// Register cash_drawer_session routes
	{
		repo := cash_drawer_session.NewRepository()
		svc := cash_drawer_session.NewService(repo, db, logger)
		handler := cash_drawer_session.NewHandler(svc, logger)
		cash_drawer_session.RegisterRoutes(r, handler)
		cash_drawer_session.RegisterAdminRoutes(r, handler)
	}

	// Register cash_movement routes
	{
		repo := cash_movement.NewRepository()
		svc := cash_movement.NewService(repo, db, logger)
		handler := cash_movement.NewHandler(svc, logger)
		cash_movement.RegisterRoutes(r, handler)
		cash_movement.RegisterAdminRoutes(r, handler)
	}

	// Register category routes
	{
		repo := category.NewRepository()
		svc := category.NewService(repo, db, logger)
		handler := category.NewHandler(svc, logger)
		category.RegisterRoutes(r, handler)
		category.RegisterAdminRoutes(r, handler)
	}

	// Register chart_of_account routes
	{
		repo := chart_of_account.NewRepository()
		svc := chart_of_account.NewService(repo, db, logger)
		handler := chart_of_account.NewHandler(svc, logger)
		chart_of_account.RegisterRoutes(r, handler)
		chart_of_account.RegisterAdminRoutes(r, handler)
	}

	// Register cours routes
	{
		repo := cours.NewRepository()
		svc := cours.NewService(repo, db, logger)
		handler := cours.NewHandler(svc, logger)
		cours.RegisterRoutes(r, handler)
		cours.RegisterAdminRoutes(r, handler)
	}

	// Register currency routes
	{
		repo := currency.NewRepository()
		svc := currency.NewService(repo, db, logger)
		handler := currency.NewHandler(svc, logger)
		currency.RegisterRoutes(r, handler)
		currency.RegisterAdminRoutes(r, handler)
	}

	// Register currency_rate routes
	{
		repo := currency_rate.NewRepository()
		svc := currency_rate.NewService(repo, db, logger)
		handler := currency_rate.NewHandler(svc, logger)
		currency_rate.RegisterRoutes(r, handler)
		currency_rate.RegisterAdminRoutes(r, handler)
	}

	// Register customer routes
	{
		repo := customer.NewRepository()
		svc := customer.NewService(repo, db, logger)
		handler := customer.NewHandler(svc, logger)
		customer.RegisterRoutes(r, handler)
		customer.RegisterAdminRoutes(r, handler)
	}

	// Register customer_address routes
	{
		repo := customer_address.NewRepository()
		svc := customer_address.NewService(repo, db, logger)
		handler := customer_address.NewHandler(svc, logger)
		customer_address.RegisterRoutes(r, handler)
		customer_address.RegisterAdminRoutes(r, handler)
	}

	// Register customer_invoice routes
	{
		repo := customer_invoice.NewRepository()
		svc := customer_invoice.NewService(repo, db, logger)
		handler := customer_invoice.NewHandler(svc, logger)
		customer_invoice.RegisterRoutes(r, handler)
		customer_invoice.RegisterAdminRoutes(r, handler)
	}

	// Register customer_invoice_line routes
	{
		repo := customer_invoice_line.NewRepository()
		svc := customer_invoice_line.NewService(repo, db, logger)
		handler := customer_invoice_line.NewHandler(svc, logger)
		customer_invoice_line.RegisterRoutes(r, handler)
		customer_invoice_line.RegisterAdminRoutes(r, handler)
	}

	// Register customer_payment routes
	{
		repo := customer_payment.NewRepository()
		svc := customer_payment.NewService(repo, db, logger)
		handler := customer_payment.NewHandler(svc, logger)
		customer_payment.RegisterRoutes(r, handler)
		customer_payment.RegisterAdminRoutes(r, handler)
	}

	// Register customer_payment_application routes
	{
		repo := customer_payment_application.NewRepository()
		svc := customer_payment_application.NewService(repo, db, logger)
		handler := customer_payment_application.NewHandler(svc, logger)
		customer_payment_application.RegisterRoutes(r, handler)
		customer_payment_application.RegisterAdminRoutes(r, handler)
	}

	// Register customer_store_credit_account routes
	{
		repo := customer_store_credit_account.NewRepository()
		svc := customer_store_credit_account.NewService(repo, db, logger)
		handler := customer_store_credit_account.NewHandler(svc, logger)
		customer_store_credit_account.RegisterRoutes(r, handler)
		customer_store_credit_account.RegisterAdminRoutes(r, handler)
	}

	// Register customer_tier_history routes
	{
		repo := customer_tier_history.NewRepository()
		svc := customer_tier_history.NewService(repo, db, logger)
		handler := customer_tier_history.NewHandler(svc, logger)
		customer_tier_history.RegisterRoutes(r, handler)
		customer_tier_history.RegisterAdminRoutes(r, handler)
	}

	// Register cycle_count routes
	{
		repo := cycle_count.NewRepository()
		svc := cycle_count.NewService(repo, db, logger)
		handler := cycle_count.NewHandler(svc, logger)
		cycle_count.RegisterRoutes(r, handler)
		cycle_count.RegisterAdminRoutes(r, handler)
	}

	// Register cycle_count_item routes
	{
		repo := cycle_count_item.NewRepository()
		svc := cycle_count_item.NewService(repo, db, logger)
		handler := cycle_count_item.NewHandler(svc, logger)
		cycle_count_item.RegisterRoutes(r, handler)
		cycle_count_item.RegisterAdminRoutes(r, handler)
	}

	// Register data_export_request routes
	{
		repo := data_export_request.NewRepository()
		svc := data_export_request.NewService(repo, db, logger)
		handler := data_export_request.NewHandler(svc, logger)
		data_export_request.RegisterRoutes(r, handler)
		data_export_request.RegisterAdminRoutes(r, handler)
	}

	// Register deferred_expense_contract routes
	{
		repo := deferred_expense_contract.NewRepository()
		svc := deferred_expense_contract.NewService(repo, db, logger)
		handler := deferred_expense_contract.NewHandler(svc, logger)
		deferred_expense_contract.RegisterRoutes(r, handler)
		deferred_expense_contract.RegisterAdminRoutes(r, handler)
	}

	// Register deferred_expense_schedule routes
	{
		repo := deferred_expense_schedule.NewRepository()
		svc := deferred_expense_schedule.NewService(repo, db, logger)
		handler := deferred_expense_schedule.NewHandler(svc, logger)
		deferred_expense_schedule.RegisterRoutes(r, handler)
		deferred_expense_schedule.RegisterAdminRoutes(r, handler)
	}

	// Register deferred_revenue_contract routes
	{
		repo := deferred_revenue_contract.NewRepository()
		svc := deferred_revenue_contract.NewService(repo, db, logger)
		handler := deferred_revenue_contract.NewHandler(svc, logger)
		deferred_revenue_contract.RegisterRoutes(r, handler)
		deferred_revenue_contract.RegisterAdminRoutes(r, handler)
	}

	// Register deferred_revenue_schedule routes
	{
		repo := deferred_revenue_schedule.NewRepository()
		svc := deferred_revenue_schedule.NewService(repo, db, logger)
		handler := deferred_revenue_schedule.NewHandler(svc, logger)
		deferred_revenue_schedule.RegisterRoutes(r, handler)
		deferred_revenue_schedule.RegisterAdminRoutes(r, handler)
	}

	// Register delivery_assignment routes
	{
		repo := delivery_assignment.NewRepository()
		svc := delivery_assignment.NewService(repo, db, logger)
		handler := delivery_assignment.NewHandler(svc, logger)
		delivery_assignment.RegisterRoutes(r, handler)
		delivery_assignment.RegisterAdminRoutes(r, handler)
	}

	// Register delivery_driver routes
	{
		repo := delivery_driver.NewRepository()
		svc := delivery_driver.NewService(repo, db, logger)
		handler := delivery_driver.NewHandler(svc, logger)
		delivery_driver.RegisterRoutes(r, handler)
		delivery_driver.RegisterAdminRoutes(r, handler)
	}

	// Register delivery_zone routes
	{
		repo := delivery_zone.NewRepository()
		svc := delivery_zone.NewService(repo, db, logger)
		handler := delivery_zone.NewHandler(svc, logger)
		delivery_zone.RegisterRoutes(r, handler)
		delivery_zone.RegisterAdminRoutes(r, handler)
	}

	// Register device routes
	{
		repo := device.NewRepository()
		svc := device.NewService(repo, db, logger)
		handler := device.NewHandler(svc, logger)
		device.RegisterRoutes(r, handler)
		device.RegisterAdminRoutes(r, handler)
	}

	// Register document_sequence routes
	{
		repo := document_sequence.NewRepository()
		svc := document_sequence.NewService(repo, db, logger)
		handler := document_sequence.NewHandler(svc, logger)
		document_sequence.RegisterRoutes(r, handler)
		document_sequence.RegisterAdminRoutes(r, handler)
	}

	// Register driver_shift routes
	{
		repo := driver_shift.NewRepository()
		svc := driver_shift.NewService(repo, db, logger)
		handler := driver_shift.NewHandler(svc, logger)
		driver_shift.RegisterRoutes(r, handler)
		driver_shift.RegisterAdminRoutes(r, handler)
	}

	// Register e_invoicing_document routes
	{
		repo := e_invoicing_document.NewRepository()
		svc := e_invoicing_document.NewService(repo, db, logger)
		handler := e_invoicing_document.NewHandler(svc, logger)
		e_invoicing_document.RegisterRoutes(r, handler)
		e_invoicing_document.RegisterAdminRoutes(r, handler)
	}

	// Register e_invoicing_document_event routes
	{
		repo := e_invoicing_document_event.NewRepository()
		svc := e_invoicing_document_event.NewService(repo, db, logger)
		handler := e_invoicing_document_event.NewHandler(svc, logger)
		e_invoicing_document_event.RegisterRoutes(r, handler)
		e_invoicing_document_event.RegisterAdminRoutes(r, handler)
	}

	// Register email_queue routes
	{
		repo := email_queue.NewRepository()
		svc := email_queue.NewService(repo, db, logger)
		handler := email_queue.NewHandler(svc, logger)
		email_queue.RegisterRoutes(r, handler)
		email_queue.RegisterAdminRoutes(r, handler)
	}

	// Register employee_schedule routes
	{
		repo := employee_schedule.NewRepository()
		svc := employee_schedule.NewService(repo, db, logger)
		handler := employee_schedule.NewHandler(svc, logger)
		employee_schedule.RegisterRoutes(r, handler)
		employee_schedule.RegisterAdminRoutes(r, handler)
	}

	// Register expens routes
	{
		repo := expens.NewRepository()
		svc := expens.NewService(repo, db, logger)
		handler := expens.NewHandler(svc, logger)
		expens.RegisterRoutes(r, handler)
		expens.RegisterAdminRoutes(r, handler)
	}

	// Register external_order_mapping routes
	{
		repo := external_order_mapping.NewRepository()
		svc := external_order_mapping.NewService(repo, db, logger)
		handler := external_order_mapping.NewHandler(svc, logger)
		external_order_mapping.RegisterRoutes(r, handler)
		external_order_mapping.RegisterAdminRoutes(r, handler)
	}

	// Register file_attachment routes
	{
		repo := file_attachment.NewRepository()
		svc := file_attachment.NewService(repo, db, logger)
		handler := file_attachment.NewHandler(svc, logger)
		file_attachment.RegisterRoutes(r, handler)
		file_attachment.RegisterAdminRoutes(r, handler)
	}

	// Register fiscal_position routes
	{
		repo := fiscal_position.NewRepository()
		svc := fiscal_position.NewService(repo, db, logger)
		handler := fiscal_position.NewHandler(svc, logger)
		fiscal_position.RegisterRoutes(r, handler)
		fiscal_position.RegisterAdminRoutes(r, handler)
	}

	// Register fiscal_position_tax_mapping routes
	{
		repo := fiscal_position_tax_mapping.NewRepository()
		svc := fiscal_position_tax_mapping.NewService(repo, db, logger)
		handler := fiscal_position_tax_mapping.NewHandler(svc, logger)
		fiscal_position_tax_mapping.RegisterRoutes(r, handler)
		fiscal_position_tax_mapping.RegisterAdminRoutes(r, handler)
	}

	// Register fiscal_year routes
	{
		repo := fiscal_year.NewRepository()
		svc := fiscal_year.NewService(repo, db, logger)
		handler := fiscal_year.NewHandler(svc, logger)
		fiscal_year.RegisterRoutes(r, handler)
		fiscal_year.RegisterAdminRoutes(r, handler)
	}

	// Register fixed_asset routes
	{
		repo := fixed_asset.NewRepository()
		svc := fixed_asset.NewService(repo, db, logger)
		handler := fixed_asset.NewHandler(svc, logger)
		fixed_asset.RegisterRoutes(r, handler)
		fixed_asset.RegisterAdminRoutes(r, handler)
	}

	// Register floor_plan routes
	{
		repo := floor_plan.NewRepository()
		svc := floor_plan.NewService(repo, db, logger)
		handler := floor_plan.NewHandler(svc, logger)
		floor_plan.RegisterRoutes(r, handler)
		floor_plan.RegisterAdminRoutes(r, handler)
	}

	// Register general_ledger routes
	{
		repo := general_ledger.NewRepository()
		svc := general_ledger.NewService(repo, db, logger)
		handler := general_ledger.NewHandler(svc, logger)
		general_ledger.RegisterRoutes(r, handler)
		general_ledger.RegisterAdminRoutes(r, handler)
	}

	// Register gift_card routes
	{
		repo := gift_card.NewRepository()
		svc := gift_card.NewService(repo, db, logger)
		handler := gift_card.NewHandler(svc, logger)
		gift_card.RegisterRoutes(r, handler)
		gift_card.RegisterAdminRoutes(r, handler)
	}

	// Register gift_card_transaction routes
	{
		repo := gift_card_transaction.NewRepository()
		svc := gift_card_transaction.NewService(repo, db, logger)
		handler := gift_card_transaction.NewHandler(svc, logger)
		gift_card_transaction.RegisterRoutes(r, handler)
		gift_card_transaction.RegisterAdminRoutes(r, handler)
	}

	// Register goods_receipt routes
	{
		repo := goods_receipt.NewRepository()
		svc := goods_receipt.NewService(repo, db, logger)
		handler := goods_receipt.NewHandler(svc, logger)
		goods_receipt.RegisterRoutes(r, handler)
		goods_receipt.RegisterAdminRoutes(r, handler)
	}

	// Register goods_receipt_item routes
	{
		repo := goods_receipt_item.NewRepository()
		svc := goods_receipt_item.NewService(repo, db, logger)
		handler := goods_receipt_item.NewHandler(svc, logger)
		goods_receipt_item.RegisterRoutes(r, handler)
		goods_receipt_item.RegisterAdminRoutes(r, handler)
	}

	// Register immutability_violations_log routes
	{
		repo := immutability_violations_log.NewRepository()
		svc := immutability_violations_log.NewService(repo, db, logger)
		handler := immutability_violations_log.NewHandler(svc, logger)
		immutability_violations_log.RegisterRoutes(r, handler)
		immutability_violations_log.RegisterAdminRoutes(r, handler)
	}

	// Register integration_config routes
	{
		repo := integration_config.NewRepository()
		svc := integration_config.NewService(repo, db, logger)
		handler := integration_config.NewHandler(svc, logger)
		integration_config.RegisterRoutes(r, handler)
		integration_config.RegisterAdminRoutes(r, handler)
	}

	// Register inventory_cost_layer routes
	{
		repo := inventory_cost_layer.NewRepository()
		svc := inventory_cost_layer.NewService(repo, db, logger)
		handler := inventory_cost_layer.NewHandler(svc, logger)
		inventory_cost_layer.RegisterRoutes(r, handler)
		inventory_cost_layer.RegisterAdminRoutes(r, handler)
	}

	// Register inventory_transaction routes
	{
		repo := inventory_transaction.NewRepository()
		svc := inventory_transaction.NewService(repo, db, logger)
		handler := inventory_transaction.NewHandler(svc, logger)
		inventory_transaction.RegisterRoutes(r, handler)
		inventory_transaction.RegisterAdminRoutes(r, handler)
	}

	// Register inventory_transfer routes
	{
		repo := inventory_transfer.NewRepository()
		svc := inventory_transfer.NewService(repo, db, logger)
		handler := inventory_transfer.NewHandler(svc, logger)
		inventory_transfer.RegisterRoutes(r, handler)
		inventory_transfer.RegisterAdminRoutes(r, handler)
	}

	// Register inventory_transfer_item routes
	{
		repo := inventory_transfer_item.NewRepository()
		svc := inventory_transfer_item.NewService(repo, db, logger)
		handler := inventory_transfer_item.NewHandler(svc, logger)
		inventory_transfer_item.RegisterRoutes(r, handler)
		inventory_transfer_item.RegisterAdminRoutes(r, handler)
	}

	// Register inventory_valuation_setting routes
	{
		repo := inventory_valuation_setting.NewRepository()
		svc := inventory_valuation_setting.NewService(repo, db, logger)
		handler := inventory_valuation_setting.NewHandler(svc, logger)
		inventory_valuation_setting.RegisterRoutes(r, handler)
		inventory_valuation_setting.RegisterAdminRoutes(r, handler)
	}

	// Register invoice_payment_schedule routes
	{
		repo := invoice_payment_schedule.NewRepository()
		svc := invoice_payment_schedule.NewService(repo, db, logger)
		handler := invoice_payment_schedule.NewHandler(svc, logger)
		invoice_payment_schedule.RegisterRoutes(r, handler)
		invoice_payment_schedule.RegisterAdminRoutes(r, handler)
	}

	// Register journal routes
	{
		repo := journal.NewRepository()
		svc := journal.NewService(repo, db, logger)
		handler := journal.NewHandler(svc, logger)
		journal.RegisterRoutes(r, handler)
		journal.RegisterAdminRoutes(r, handler)
	}

	// Register journal_entry routes
	{
		repo := journal_entry.NewRepository()
		svc := journal_entry.NewService(repo, db, logger)
		handler := journal_entry.NewHandler(svc, logger)
		journal_entry.RegisterRoutes(r, handler)
		journal_entry.RegisterAdminRoutes(r, handler)
	}

	// Register journal_entry_line routes
	{
		repo := journal_entry_line.NewRepository()
		svc := journal_entry_line.NewService(repo, db, logger)
		handler := journal_entry_line.NewHandler(svc, logger)
		journal_entry_line.RegisterRoutes(r, handler)
		journal_entry_line.RegisterAdminRoutes(r, handler)
	}

	// Register journal_entry_type routes
	{
		repo := journal_entry_type.NewRepository()
		svc := journal_entry_type.NewService(repo, db, logger)
		handler := journal_entry_type.NewHandler(svc, logger)
		journal_entry_type.RegisterRoutes(r, handler)
		journal_entry_type.RegisterAdminRoutes(r, handler)
	}

	// Register kitchen_station routes
	{
		repo := kitchen_station.NewRepository()
		svc := kitchen_station.NewService(repo, db, logger)
		handler := kitchen_station.NewHandler(svc, logger)
		kitchen_station.RegisterRoutes(r, handler)
		kitchen_station.RegisterAdminRoutes(r, handler)
	}

	// Register kitchen_ticket routes
	{
		repo := kitchen_ticket.NewRepository()
		svc := kitchen_ticket.NewService(repo, db, logger)
		handler := kitchen_ticket.NewHandler(svc, logger)
		kitchen_ticket.RegisterRoutes(r, handler)
		kitchen_ticket.RegisterAdminRoutes(r, handler)
	}

	// Register localization_package routes
	{
		repo := localization_package.NewRepository()
		svc := localization_package.NewService(repo, db, logger)
		handler := localization_package.NewHandler(svc, logger)
		localization_package.RegisterRoutes(r, handler)
		localization_package.RegisterAdminRoutes(r, handler)
	}

	// Register location routes
	{
		repo := location.NewRepository()
		svc := location.NewService(repo, db, logger)
		handler := location.NewHandler(svc, logger)
		location.RegisterRoutes(r, handler)
		location.RegisterAdminRoutes(r, handler)
	}

	// Register loyalty_points_rule routes
	{
		repo := loyalty_points_rule.NewRepository()
		svc := loyalty_points_rule.NewService(repo, db, logger)
		handler := loyalty_points_rule.NewHandler(svc, logger)
		loyalty_points_rule.RegisterRoutes(r, handler)
		loyalty_points_rule.RegisterAdminRoutes(r, handler)
	}

	// Register loyalty_points_transaction routes
	{
		repo := loyalty_points_transaction.NewRepository()
		svc := loyalty_points_transaction.NewService(repo, db, logger)
		handler := loyalty_points_transaction.NewHandler(svc, logger)
		loyalty_points_transaction.RegisterRoutes(r, handler)
		loyalty_points_transaction.RegisterAdminRoutes(r, handler)
	}

	// Register loyalty_redemption routes
	{
		repo := loyalty_redemption.NewRepository()
		svc := loyalty_redemption.NewService(repo, db, logger)
		handler := loyalty_redemption.NewHandler(svc, logger)
		loyalty_redemption.RegisterRoutes(r, handler)
		loyalty_redemption.RegisterAdminRoutes(r, handler)
	}

	// Register loyalty_reward routes
	{
		repo := loyalty_reward.NewRepository()
		svc := loyalty_reward.NewService(repo, db, logger)
		handler := loyalty_reward.NewHandler(svc, logger)
		loyalty_reward.RegisterRoutes(r, handler)
		loyalty_reward.RegisterAdminRoutes(r, handler)
	}

	// Register loyalty_tier routes
	{
		repo := loyalty_tier.NewRepository()
		svc := loyalty_tier.NewService(repo, db, logger)
		handler := loyalty_tier.NewHandler(svc, logger)
		loyalty_tier.RegisterRoutes(r, handler)
		loyalty_tier.RegisterAdminRoutes(r, handler)
	}

	// Register loyalty_tier_benefit routes
	{
		repo := loyalty_tier_benefit.NewRepository()
		svc := loyalty_tier_benefit.NewService(repo, db, logger)
		handler := loyalty_tier_benefit.NewHandler(svc, logger)
		loyalty_tier_benefit.RegisterRoutes(r, handler)
		loyalty_tier_benefit.RegisterAdminRoutes(r, handler)
	}

	// Register modifier routes
	{
		repo := modifier.NewRepository()
		svc := modifier.NewService(repo, db, logger)
		handler := modifier.NewHandler(svc, logger)
		modifier.RegisterRoutes(r, handler)
		modifier.RegisterAdminRoutes(r, handler)
	}

	// Register modifier_group routes
	{
		repo := modifier_group.NewRepository()
		svc := modifier_group.NewService(repo, db, logger)
		handler := modifier_group.NewHandler(svc, logger)
		modifier_group.RegisterRoutes(r, handler)
		modifier_group.RegisterAdminRoutes(r, handler)
	}

	// Register notification routes
	{
		repo := notification.NewRepository()
		svc := notification.NewService(repo, db, logger)
		handler := notification.NewHandler(svc, logger)
		notification.RegisterRoutes(r, handler)
		notification.RegisterAdminRoutes(r, handler)
	}

	// Register notification_preference routes
	{
		repo := notification_preference.NewRepository()
		svc := notification_preference.NewService(repo, db, logger)
		handler := notification_preference.NewHandler(svc, logger)
		notification_preference.RegisterRoutes(r, handler)
		notification_preference.RegisterAdminRoutes(r, handler)
	}

	// Register order routes
	{
		repo := order.NewRepository()
		svc := order.NewService(repo, db, logger)
		handler := order.NewHandler(svc, logger)
		order.RegisterRoutes(r, handler)
		order.RegisterAdminRoutes(r, handler)
	}

	// Register order_item routes
	{
		repo := order_item.NewRepository()
		svc := order_item.NewService(repo, db, logger)
		handler := order_item.NewHandler(svc, logger)
		order_item.RegisterRoutes(r, handler)
		order_item.RegisterAdminRoutes(r, handler)
	}

	// Register order_item_modifier routes
	{
		repo := order_item_modifier.NewRepository()
		svc := order_item_modifier.NewService(repo, db, logger)
		handler := order_item_modifier.NewHandler(svc, logger)
		order_item_modifier.RegisterRoutes(r, handler)
		order_item_modifier.RegisterAdminRoutes(r, handler)
	}

	// Register order_tracking_event routes
	{
		repo := order_tracking_event.NewRepository()
		svc := order_tracking_event.NewService(repo, db, logger)
		handler := order_tracking_event.NewHandler(svc, logger)
		order_tracking_event.RegisterRoutes(r, handler)
		order_tracking_event.RegisterAdminRoutes(r, handler)
	}

	// Register organization routes
	{
		repo := organization.NewRepository()
		svc := organization.NewService(repo, db, logger)
		handler := organization.NewHandler(svc, logger)
		organization.RegisterRoutes(r, handler)
		organization.RegisterAdminRoutes(r, handler)
	}

	// Register organization_feature routes
	{
		repo := organization_feature.NewRepository()
		svc := organization_feature.NewService(repo, db, logger)
		handler := organization_feature.NewHandler(svc, logger)
		organization_feature.RegisterRoutes(r, handler)
		organization_feature.RegisterAdminRoutes(r, handler)
	}

	// Register organization_setting routes
	{
		repo := organization_setting.NewRepository()
		svc := organization_setting.NewService(repo, db, logger)
		handler := organization_setting.NewHandler(svc, logger)
		organization_setting.RegisterRoutes(r, handler)
		organization_setting.RegisterAdminRoutes(r, handler)
	}

	// Register payment routes
	{
		repo := payment.NewRepository()
		svc := payment.NewService(repo, db, logger)
		handler := payment.NewHandler(svc, logger)
		payment.RegisterRoutes(r, handler)
		payment.RegisterAdminRoutes(r, handler)
	}

	// Register payment_term routes
	{
		repo := payment_term.NewRepository()
		svc := payment_term.NewService(repo, db, logger)
		handler := payment_term.NewHandler(svc, logger)
		payment_term.RegisterRoutes(r, handler)
		payment_term.RegisterAdminRoutes(r, handler)
	}

	// Register payment_term_line routes
	{
		repo := payment_term_line.NewRepository()
		svc := payment_term_line.NewService(repo, db, logger)
		handler := payment_term_line.NewHandler(svc, logger)
		payment_term_line.RegisterRoutes(r, handler)
		payment_term_line.RegisterAdminRoutes(r, handler)
	}

	// Register permission routes
	{
		repo := permission.NewRepository()
		svc := permission.NewService(repo, db, logger)
		handler := permission.NewHandler(svc, logger)
		permission.RegisterRoutes(r, handler)
		permission.RegisterAdminRoutes(r, handler)
	}

	// Register pos_account_mapping routes
	{
		repo := pos_account_mapping.NewRepository()
		svc := pos_account_mapping.NewService(repo, db, logger)
		handler := pos_account_mapping.NewHandler(svc, logger)
		pos_account_mapping.RegisterRoutes(r, handler)
		pos_account_mapping.RegisterAdminRoutes(r, handler)
	}

	// Register pos_error_log routes
	{
		repo := pos_error_log.NewRepository()
		svc := pos_error_log.NewService(repo, db, logger)
		handler := pos_error_log.NewHandler(svc, logger)
		pos_error_log.RegisterRoutes(r, handler)
		pos_error_log.RegisterAdminRoutes(r, handler)
	}

	// Register pos_posting_audit routes
	{
		repo := pos_posting_audit.NewRepository()
		svc := pos_posting_audit.NewService(repo, db, logger)
		handler := pos_posting_audit.NewHandler(svc, logger)
		pos_posting_audit.RegisterRoutes(r, handler)
		pos_posting_audit.RegisterAdminRoutes(r, handler)
	}

	// Register pos_session routes
	{
		repo := pos_session.NewRepository()
		svc := pos_session.NewService(repo, db, logger)
		handler := pos_session.NewHandler(svc, logger)
		pos_session.RegisterRoutes(r, handler)
		pos_session.RegisterAdminRoutes(r, handler)
	}

	// Register pos_tax_mapping routes
	{
		repo := pos_tax_mapping.NewRepository()
		svc := pos_tax_mapping.NewService(repo, db, logger)
		handler := pos_tax_mapping.NewHandler(svc, logger)
		pos_tax_mapping.RegisterRoutes(r, handler)
		pos_tax_mapping.RegisterAdminRoutes(r, handler)
	}

	// Register posting_concept routes
	{
		repo := posting_concept.NewRepository()
		svc := posting_concept.NewService(repo, db, logger)
		handler := posting_concept.NewHandler(svc, logger)
		posting_concept.RegisterRoutes(r, handler)
		posting_concept.RegisterAdminRoutes(r, handler)
	}

	// Register posting_concept_override routes
	{
		repo := posting_concept_override.NewRepository()
		svc := posting_concept_override.NewService(repo, db, logger)
		handler := posting_concept_override.NewHandler(svc, logger)
		posting_concept_override.RegisterRoutes(r, handler)
		posting_concept_override.RegisterAdminRoutes(r, handler)
	}

	// Register posting_document_type routes
	{
		repo := posting_document_type.NewRepository()
		svc := posting_document_type.NewService(repo, db, logger)
		handler := posting_document_type.NewHandler(svc, logger)
		posting_document_type.RegisterRoutes(r, handler)
		posting_document_type.RegisterAdminRoutes(r, handler)
	}

	// Register posting_profile routes
	{
		repo := posting_profile.NewRepository()
		svc := posting_profile.NewService(repo, db, logger)
		handler := posting_profile.NewHandler(svc, logger)
		posting_profile.RegisterRoutes(r, handler)
		posting_profile.RegisterAdminRoutes(r, handler)
	}

	// Register posting_profile_document routes
	{
		repo := posting_profile_document.NewRepository()
		svc := posting_profile_document.NewService(repo, db, logger)
		handler := posting_profile_document.NewHandler(svc, logger)
		posting_profile_document.RegisterRoutes(r, handler)
		posting_profile_document.RegisterAdminRoutes(r, handler)
	}

	// Register posting_rule routes
	{
		repo := posting_rule.NewRepository()
		svc := posting_rule.NewService(repo, db, logger)
		handler := posting_rule.NewHandler(svc, logger)
		posting_rule.RegisterRoutes(r, handler)
		posting_rule.RegisterAdminRoutes(r, handler)
	}

	// Register posting_rule_line routes
	{
		repo := posting_rule_line.NewRepository()
		svc := posting_rule_line.NewService(repo, db, logger)
		handler := posting_rule_line.NewHandler(svc, logger)
		posting_rule_line.RegisterRoutes(r, handler)
		posting_rule_line.RegisterAdminRoutes(r, handler)
	}

	// Register posting_validation_result routes
	{
		repo := posting_validation_result.NewRepository()
		svc := posting_validation_result.NewService(repo, db, logger)
		handler := posting_validation_result.NewHandler(svc, logger)
		posting_validation_result.RegisterRoutes(r, handler)
		posting_validation_result.RegisterAdminRoutes(r, handler)
	}

	// Register posting_validation_rule routes
	{
		repo := posting_validation_rule.NewRepository()
		svc := posting_validation_rule.NewService(repo, db, logger)
		handler := posting_validation_rule.NewHandler(svc, logger)
		posting_validation_rule.RegisterRoutes(r, handler)
		posting_validation_rule.RegisterAdminRoutes(r, handler)
	}

	// Register price_list routes
	{
		repo := price_list.NewRepository()
		svc := price_list.NewService(repo, db, logger)
		handler := price_list.NewHandler(svc, logger)
		price_list.RegisterRoutes(r, handler)
		price_list.RegisterAdminRoutes(r, handler)
	}

	// Register price_list_item routes
	{
		repo := price_list_item.NewRepository()
		svc := price_list_item.NewService(repo, db, logger)
		handler := price_list_item.NewHandler(svc, logger)
		price_list_item.RegisterRoutes(r, handler)
		price_list_item.RegisterAdminRoutes(r, handler)
	}

	// Register printer_configuration routes
	{
		repo := printer_configuration.NewRepository()
		svc := printer_configuration.NewService(repo, db, logger)
		handler := printer_configuration.NewHandler(svc, logger)
		printer_configuration.RegisterRoutes(r, handler)
		printer_configuration.RegisterAdminRoutes(r, handler)
	}

	// Register product routes
	{
		repo := product.NewRepository()
		svc := product.NewService(repo, db, logger)
		handler := product.NewHandler(svc, logger)
		product.RegisterRoutes(r, handler)
		product.RegisterAdminRoutes(r, handler)
	}

	// Register product_batch routes
	{
		repo := product_batch.NewRepository()
		svc := product_batch.NewService(repo, db, logger)
		handler := product_batch.NewHandler(svc, logger)
		product_batch.RegisterRoutes(r, handler)
		product_batch.RegisterAdminRoutes(r, handler)
	}

	// Register product_component routes
	{
		repo := product_component.NewRepository()
		svc := product_component.NewService(repo, db, logger)
		handler := product_component.NewHandler(svc, logger)
		product_component.RegisterRoutes(r, handler)
		product_component.RegisterAdminRoutes(r, handler)
	}

	// Register product_modifier_group routes
	{
		repo := product_modifier_group.NewRepository()
		svc := product_modifier_group.NewService(repo, db, logger)
		handler := product_modifier_group.NewHandler(svc, logger)
		product_modifier_group.RegisterRoutes(r, handler)
		product_modifier_group.RegisterAdminRoutes(r, handler)
	}

	// Register product_serial_number routes
	{
		repo := product_serial_number.NewRepository()
		svc := product_serial_number.NewService(repo, db, logger)
		handler := product_serial_number.NewHandler(svc, logger)
		product_serial_number.RegisterRoutes(r, handler)
		product_serial_number.RegisterAdminRoutes(r, handler)
	}

	// Register product_variant routes
	{
		repo := product_variant.NewRepository()
		svc := product_variant.NewService(repo, db, logger)
		handler := product_variant.NewHandler(svc, logger)
		product_variant.RegisterRoutes(r, handler)
		product_variant.RegisterAdminRoutes(r, handler)
	}

	// Register promotion routes
	{
		repo := promotion.NewRepository()
		svc := promotion.NewService(repo, db, logger)
		handler := promotion.NewHandler(svc, logger)
		promotion.RegisterRoutes(r, handler)
		promotion.RegisterAdminRoutes(r, handler)
	}

	// Register promotion_usage routes
	{
		repo := promotion_usage.NewRepository()
		svc := promotion_usage.NewService(repo, db, logger)
		handler := promotion_usage.NewHandler(svc, logger)
		promotion_usage.RegisterRoutes(r, handler)
		promotion_usage.RegisterAdminRoutes(r, handler)
	}

	// Register purchase_order routes
	{
		repo := purchase_order.NewRepository()
		svc := purchase_order.NewService(repo, db, logger)
		handler := purchase_order.NewHandler(svc, logger)
		purchase_order.RegisterRoutes(r, handler)
		purchase_order.RegisterAdminRoutes(r, handler)
	}

	// Register purchase_order_item routes
	{
		repo := purchase_order_item.NewRepository()
		svc := purchase_order_item.NewService(repo, db, logger)
		handler := purchase_order_item.NewHandler(svc, logger)
		purchase_order_item.RegisterRoutes(r, handler)
		purchase_order_item.RegisterAdminRoutes(r, handler)
	}

	// Register rate_limit routes
	{
		repo := rate_limit.NewRepository()
		svc := rate_limit.NewService(repo, db, logger)
		handler := rate_limit.NewHandler(svc, logger)
		rate_limit.RegisterRoutes(r, handler)
		rate_limit.RegisterAdminRoutes(r, handler)
	}

	// Register reconciliation_rule_model routes
	{
		repo := reconciliation_rule_model.NewRepository()
		svc := reconciliation_rule_model.NewService(repo, db, logger)
		handler := reconciliation_rule_model.NewHandler(svc, logger)
		reconciliation_rule_model.RegisterRoutes(r, handler)
		reconciliation_rule_model.RegisterAdminRoutes(r, handler)
	}

	// Register reservation routes
	{
		repo := reservation.NewRepository()
		svc := reservation.NewService(repo, db, logger)
		handler := reservation.NewHandler(svc, logger)
		reservation.RegisterRoutes(r, handler)
		reservation.RegisterAdminRoutes(r, handler)
	}

	// Register restaurant_table routes
	{
		repo := restaurant_table.NewRepository()
		svc := restaurant_table.NewService(repo, db, logger)
		handler := restaurant_table.NewHandler(svc, logger)
		restaurant_table.RegisterRoutes(r, handler)
		restaurant_table.RegisterAdminRoutes(r, handler)
	}

	// Register return_reason routes
	{
		repo := return_reason.NewRepository()
		svc := return_reason.NewService(repo, db, logger)
		handler := return_reason.NewHandler(svc, logger)
		return_reason.RegisterRoutes(r, handler)
		return_reason.RegisterAdminRoutes(r, handler)
	}

	// Register role routes
	{
		repo := role.NewRepository()
		svc := role.NewService(repo, db, logger)
		handler := role.NewHandler(svc, logger)
		role.RegisterRoutes(r, handler)
		role.RegisterAdminRoutes(r, handler)
	}

	// Register role_permission routes
	{
		repo := role_permission.NewRepository()
		svc := role_permission.NewService(repo, db, logger)
		handler := role_permission.NewHandler(svc, logger)
		role_permission.RegisterRoutes(r, handler)
		role_permission.RegisterAdminRoutes(r, handler)
	}

	// Register sale routes
	{
		repo := sale.NewRepository()
		svc := sale.NewService(repo, db, logger)
		handler := sale.NewHandler(svc, logger)
		sale.RegisterRoutes(r, handler)
		sale.RegisterAdminRoutes(r, handler)
	}

	// Register sale_item routes
	{
		repo := sale_item.NewRepository()
		svc := sale_item.NewService(repo, db, logger)
		handler := sale_item.NewHandler(svc, logger)
		sale_item.RegisterRoutes(r, handler)
		sale_item.RegisterAdminRoutes(r, handler)
	}

	// Register sale_return routes
	{
		repo := sale_return.NewRepository()
		svc := sale_return.NewService(repo, db, logger)
		handler := sale_return.NewHandler(svc, logger)
		sale_return.RegisterRoutes(r, handler)
		sale_return.RegisterAdminRoutes(r, handler)
	}

	// Register sale_return_item routes
	{
		repo := sale_return_item.NewRepository()
		svc := sale_return_item.NewService(repo, db, logger)
		handler := sale_return_item.NewHandler(svc, logger)
		sale_return_item.RegisterRoutes(r, handler)
		sale_return_item.RegisterAdminRoutes(r, handler)
	}

	// Register sales_channel routes
	{
		repo := sales_channel.NewRepository()
		svc := sales_channel.NewService(repo, db, logger)
		handler := sales_channel.NewHandler(svc, logger)
		sales_channel.RegisterRoutes(r, handler)
		sales_channel.RegisterAdminRoutes(r, handler)
	}

	// Register scheduled_report routes
	{
		repo := scheduled_report.NewRepository()
		svc := scheduled_report.NewService(repo, db, logger)
		handler := scheduled_report.NewHandler(svc, logger)
		scheduled_report.RegisterRoutes(r, handler)
		scheduled_report.RegisterAdminRoutes(r, handler)
	}

	// Register shift routes
	{
		repo := shift.NewRepository()
		svc := shift.NewService(repo, db, logger)
		handler := shift.NewHandler(svc, logger)
		shift.RegisterRoutes(r, handler)
		shift.RegisterAdminRoutes(r, handler)
	}

	// Register sms_queue routes
	{
		repo := sms_queue.NewRepository()
		svc := sms_queue.NewService(repo, db, logger)
		handler := sms_queue.NewHandler(svc, logger)
		sms_queue.RegisterRoutes(r, handler)
		sms_queue.RegisterAdminRoutes(r, handler)
	}

	// Register staff_commission routes
	{
		repo := staff_commission.NewRepository()
		svc := staff_commission.NewService(repo, db, logger)
		handler := staff_commission.NewHandler(svc, logger)
		staff_commission.RegisterRoutes(r, handler)
		staff_commission.RegisterAdminRoutes(r, handler)
	}

	// Register stock_adjustment_reason routes
	{
		repo := stock_adjustment_reason.NewRepository()
		svc := stock_adjustment_reason.NewService(repo, db, logger)
		handler := stock_adjustment_reason.NewHandler(svc, logger)
		stock_adjustment_reason.RegisterRoutes(r, handler)
		stock_adjustment_reason.RegisterAdminRoutes(r, handler)
	}

	// Register store_credit_transaction routes
	{
		repo := store_credit_transaction.NewRepository()
		svc := store_credit_transaction.NewService(repo, db, logger)
		handler := store_credit_transaction.NewHandler(svc, logger)
		store_credit_transaction.RegisterRoutes(r, handler)
		store_credit_transaction.RegisterAdminRoutes(r, handler)
	}

	// Register supplier routes
	{
		repo := supplier.NewRepository()
		svc := supplier.NewService(repo, db, logger)
		handler := supplier.NewHandler(svc, logger)
		supplier.RegisterRoutes(r, handler)
		supplier.RegisterAdminRoutes(r, handler)
	}

	// Register system_health routes
	{
		repo := system_health.NewRepository()
		svc := system_health.NewService(repo, db, logger)
		handler := system_health.NewHandler(svc, logger)
		system_health.RegisterRoutes(r, handler)
		system_health.RegisterAdminRoutes(r, handler)
	}

	// Register table_section routes
	{
		repo := table_section.NewRepository()
		svc := table_section.NewService(repo, db, logger)
		handler := table_section.NewHandler(svc, logger)
		table_section.RegisterRoutes(r, handler)
		table_section.RegisterAdminRoutes(r, handler)
	}

	// Register tax routes
	{
		repo := tax.NewRepository()
		svc := tax.NewService(repo, db, logger)
		handler := tax.NewHandler(svc, logger)
		tax.RegisterRoutes(r, handler)
		tax.RegisterAdminRoutes(r, handler)
	}

	// Register tax_group routes
	{
		repo := tax_group.NewRepository()
		svc := tax_group.NewService(repo, db, logger)
		handler := tax_group.NewHandler(svc, logger)
		tax_group.RegisterRoutes(r, handler)
		tax_group.RegisterAdminRoutes(r, handler)
	}

	// Register tax_report_definition routes
	{
		repo := tax_report_definition.NewRepository()
		svc := tax_report_definition.NewService(repo, db, logger)
		handler := tax_report_definition.NewHandler(svc, logger)
		tax_report_definition.RegisterRoutes(r, handler)
		tax_report_definition.RegisterAdminRoutes(r, handler)
	}

	// Register tax_report_line routes
	{
		repo := tax_report_line.NewRepository()
		svc := tax_report_line.NewService(repo, db, logger)
		handler := tax_report_line.NewHandler(svc, logger)
		tax_report_line.RegisterRoutes(r, handler)
		tax_report_line.RegisterAdminRoutes(r, handler)
	}

	// Register time_clock_entry routes
	{
		repo := time_clock_entry.NewRepository()
		svc := time_clock_entry.NewService(repo, db, logger)
		handler := time_clock_entry.NewHandler(svc, logger)
		time_clock_entry.RegisterRoutes(r, handler)
		time_clock_entry.RegisterAdminRoutes(r, handler)
	}

	// Register tip_distribution routes
	{
		repo := tip_distribution.NewRepository()
		svc := tip_distribution.NewService(repo, db, logger)
		handler := tip_distribution.NewHandler(svc, logger)
		tip_distribution.RegisterRoutes(r, handler)
		tip_distribution.RegisterAdminRoutes(r, handler)
	}

	// Register tip_pool routes
	{
		repo := tip_pool.NewRepository()
		svc := tip_pool.NewService(repo, db, logger)
		handler := tip_pool.NewHandler(svc, logger)
		tip_pool.RegisterRoutes(r, handler)
		tip_pool.RegisterAdminRoutes(r, handler)
	}

	// Register units_of_measure routes
	{
		repo := units_of_measure.NewRepository()
		svc := units_of_measure.NewService(repo, db, logger)
		handler := units_of_measure.NewHandler(svc, logger)
		units_of_measure.RegisterRoutes(r, handler)
		units_of_measure.RegisterAdminRoutes(r, handler)
	}

	// Register uom_conversion routes
	{
		repo := uom_conversion.NewRepository()
		svc := uom_conversion.NewService(repo, db, logger)
		handler := uom_conversion.NewHandler(svc, logger)
		uom_conversion.RegisterRoutes(r, handler)
		uom_conversion.RegisterAdminRoutes(r, handler)
	}

	// Register user routes
	{
		repo := user.NewRepository()
		svc := user.NewService(repo, db, logger)
		handler := user.NewHandler(svc, logger)
		user.RegisterRoutes(r, handler)
		user.RegisterAdminRoutes(r, handler)
	}

	// Register user_role routes
	{
		repo := user_role.NewRepository()
		svc := user_role.NewService(repo, db, logger)
		handler := user_role.NewHandler(svc, logger)
		user_role.RegisterRoutes(r, handler)
		user_role.RegisterAdminRoutes(r, handler)
	}

	// Register user_session routes
	{
		repo := user_session.NewRepository()
		svc := user_session.NewService(repo, db, logger)
		handler := user_session.NewHandler(svc, logger)
		user_session.RegisterRoutes(r, handler)
		user_session.RegisterAdminRoutes(r, handler)
	}

	// Register user_setting routes
	{
		repo := user_setting.NewRepository()
		svc := user_setting.NewService(repo, db, logger)
		handler := user_setting.NewHandler(svc, logger)
		user_setting.RegisterRoutes(r, handler)
		user_setting.RegisterAdminRoutes(r, handler)
	}

	// Register vendor_bill routes
	{
		repo := vendor_bill.NewRepository()
		svc := vendor_bill.NewService(repo, db, logger)
		handler := vendor_bill.NewHandler(svc, logger)
		vendor_bill.RegisterRoutes(r, handler)
		vendor_bill.RegisterAdminRoutes(r, handler)
	}

	// Register vendor_bill_line routes
	{
		repo := vendor_bill_line.NewRepository()
		svc := vendor_bill_line.NewService(repo, db, logger)
		handler := vendor_bill_line.NewHandler(svc, logger)
		vendor_bill_line.RegisterRoutes(r, handler)
		vendor_bill_line.RegisterAdminRoutes(r, handler)
	}

	// Register vendor_payment routes
	{
		repo := vendor_payment.NewRepository()
		svc := vendor_payment.NewService(repo, db, logger)
		handler := vendor_payment.NewHandler(svc, logger)
		vendor_payment.RegisterRoutes(r, handler)
		vendor_payment.RegisterAdminRoutes(r, handler)
	}

	// Register vendor_payment_application routes
	{
		repo := vendor_payment_application.NewRepository()
		svc := vendor_payment_application.NewService(repo, db, logger)
		handler := vendor_payment_application.NewHandler(svc, logger)
		vendor_payment_application.RegisterRoutes(r, handler)
		vendor_payment_application.RegisterAdminRoutes(r, handler)
	}

	// Register webhook routes
	{
		repo := webhook.NewRepository()
		svc := webhook.NewService(repo, db, logger)
		handler := webhook.NewHandler(svc, logger)
		webhook.RegisterRoutes(r, handler)
		webhook.RegisterAdminRoutes(r, handler)
	}

	// Register webhook_delivery routes
	{
		repo := webhook_delivery.NewRepository()
		svc := webhook_delivery.NewService(repo, db, logger)
		handler := webhook_delivery.NewHandler(svc, logger)
		webhook_delivery.RegisterRoutes(r, handler)
		webhook_delivery.RegisterAdminRoutes(r, handler)
	}

	// Register your_table_name routes
	{
		repo := your_table_name.NewRepository()
		svc := your_table_name.NewService(repo, db, logger)
		handler := your_table_name.NewHandler(svc, logger)
		your_table_name.RegisterRoutes(r, handler)
		your_table_name.RegisterAdminRoutes(r, handler)
	}

	logger.Info("registered routes for 171 modules")
}
